// <auto-generated />
using System;
using DOS.Agenda.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DOS.Agenda.Data.Migrations
{
    [DbContext(typeof(HorarioContext))]
    partial class HorarioContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DOS.Agenda.Domain.Horario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime");

                    b.Property<int>("VagasOcupadas")
                        .HasColumnType("int");

                    b.Property<int>("VagasTotais")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Horarios", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
